# Generated by Django 6.0.7 on 2026-07-23 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('tasks', '0001_initial'),
        ('tracker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeEntryEditRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_start_time', models.DateTimeField(blank=True, null=True)),
                ('requested_end_time', models.DateTimeField(blank=True, null=True)),
                ('requested_description', models.TextField(blank=True)),
                ('requested_billable', models.BooleanField(default=True)),
                ('reason', models.TextField()),
                ('proof_screenshot', models.ImageField(blank=True, null=True, upload_to='time_entry_edit_requests/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('manager_comment', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entry_edit_requests', to=settings.AUTH_USER_MODEL)),
                ('requested_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_entry_edit_requests', to='projects.project')),
                ('requested_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_entry_edit_requests', to='tasks.task')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_time_entry_requests', to=settings.AUTH_USER_MODEL)),
                ('time_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_requests', to='tracker.timeentry')),
            ],
        ),
    ]
