# Generated by Django 6.0.7 on 2026-08-05 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeentryeditrequest',
            options={'ordering': ('-requested_at',), 'verbose_name': 'Time Entry Edit Request', 'verbose_name_plural': 'Time Entry Edit Requests'},
        ),
    ]
