# Generated by Django 6.0.7 on 2026-08-11 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_leaverequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('allocated_days', models.DecimalField(decimal_places=2, max_digits=5)),
                ('used_days', models.DecimalField(decimal_places=2, max_digits=5)),
                ('unused_days', models.DecimalField(decimal_places=2, max_digits=5)),
                ('daily_salary_rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('converted_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_settlements', to=settings.AUTH_USER_MODEL)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='leave.leavetype')),
                ('processed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processed_leave_settlements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Leave Settlement',
                'verbose_name_plural': 'Leave Settlements',
                'ordering': ('-year', 'employee', 'leave_type'),
                'constraints': [models.UniqueConstraint(fields=('employee', 'leave_type', 'year'), name='unique_leave_settlement_per_year')],
            },
        ),
    ]
